import type { AnalysisDownload } from './api.ts';

/** Save a response already authorized and generated by the backend. */
export function saveAnalysisDownload(download: AnalysisDownload): void {
  const url = URL.createObjectURL(download.blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = download.filename;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
