/** Real sequence from the frozen human_positive_line_1 baseline; no example predictions. */
export const EXAMPLE_NAME = 'human_positive_line_1';
export const EXAMPLE_SEQUENCE = 'MSGGGVIRGPAGNNDCRIYVGNLPPDIRTKDIEDVFYKYGAIRDIDLKNRRGGPPFAFVEFEDPRDAEDAVYGRDGYDYDGYRLRVEFPRSGRGTGRGGGGGGGGGAPRGRYGPPSRRSENRVVVSGLPPSGSWQDLKDHMREAGDVCYADVYRDGTGVVEFVRKEDMTYAVRKLDNTKFRSHEGETAYIRVKVDGPRSPSYGRSRSRSRSRSRSRSRSNSRSRSYSPRRSRGSPRYSPRHSRSRSRT';
export const EXAMPLE_FASTA = `>${EXAMPLE_NAME}\n${EXAMPLE_SEQUENCE}`;
export const EXAMPLE_SOURCE = 'LRECA human test dataset, positive line 1; sequence example only.';
